ejabberd:
  image: rroemhild/ejabberd
  ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
  environment:
    - ERLANG_NODE=ejabberd
    - XMPP_DOMAIN=example.com xyz.io
    - EJABBERD_AUTH_METHOD=external
    - EJABBERD_EXTAUTH_PROGRAM=/opt/ejabberd/scripts/lib/auth_mysql.py
    - EJABBERD_EXTAUTH_INSTANCES=3
    - EJABBERD_EXTAUTH_CACHE=600
    - EJABBERD_SQL_MODE=true
    - AUTH_MYSQL_HOST=localhost
    - AUTH_MYSQL_USER=user
    - AUTH_MYSQL_PASSWORD=password
    - AUTH_MYSQL_DATABASE=database
    - AUTH_MYSQL_QUERY_GETPASS=SELECT jabber_password FROM users WHERE jabber_username = %(user)s
    - AUTH_MYSQL_HASHALG=sha256
    - EJABBERD_ADMINS=admin@example.com
